# Generated by Django 6.0 on 2026-03-23 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModelePrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_modele', models.CharField(default='Logistic Regression', max_length=100)),
                ('precision', models.FloatField(default=0.0)),
                ('date_entrainement', models.DateField()),
                ('fichier_modele', models.CharField(default='modele_logistic_regression.pkl', max_length=200)),
                ('description', models.TextField(blank=True)),
                ('actif', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Modèle de Prédiction',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('poste', models.CharField(max_length=200)),
                ('date_embauche', models.DateField()),
                ('salaire', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif')], default='actif', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employees/')),
                ('age', models.IntegerField(default=30)),
                ('gender', models.CharField(choices=[('Male', 'Homme'), ('Female', 'Femme')], default='Male', max_length=10)),
                ('marital_status', models.CharField(choices=[('Single', 'Célibataire'), ('Married', 'Marié(e)'), ('Divorced', 'Divorcé(e)')], default='Single', max_length=10)),
                ('distance_from_home', models.IntegerField(default=5)),
                ('education', models.IntegerField(default=3)),
                ('education_field', models.CharField(choices=[('Life Sciences', 'Life Sciences'), ('Medical', 'Medical'), ('Marketing', 'Marketing'), ('Technical Degree', 'Technical Degree'), ('Human Resources', 'Human Resources'), ('Other', 'Other')], default='Life Sciences', max_length=50)),
                ('job_role', models.CharField(choices=[('Sales Executive', 'Sales Executive'), ('Research Scientist', 'Research Scientist'), ('Laboratory Technician', 'Laboratory Technician'), ('Manufacturing Director', 'Manufacturing Director'), ('Healthcare Representative', 'Healthcare Representative'), ('Manager', 'Manager'), ('Sales Representative', 'Sales Representative'), ('Research Director', 'Research Director'), ('Human Resources', 'Human Resources')], default='Research Scientist', max_length=50)),
                ('job_level', models.IntegerField(default=2)),
                ('business_travel', models.CharField(choices=[('Non-Travel', 'Jamais'), ('Travel_Rarely', 'Rarement'), ('Travel_Frequently', 'Fréquemment')], default='Travel_Rarely', max_length=20)),
                ('overtime', models.CharField(choices=[('No', 'Non'), ('Yes', 'Oui')], default='No', max_length=3)),
                ('daily_rate', models.IntegerField(default=800)),
                ('hourly_rate', models.IntegerField(default=66)),
                ('monthly_income', models.IntegerField(default=6500)),
                ('monthly_rate', models.IntegerField(default=14000)),
                ('percent_salary_hike', models.IntegerField(default=15)),
                ('stock_option_level', models.IntegerField(default=1)),
                ('total_working_years', models.IntegerField(default=8)),
                ('num_companies_worked', models.IntegerField(default=2)),
                ('years_at_company', models.IntegerField(default=5)),
                ('years_in_current_role', models.IntegerField(default=3)),
                ('years_since_last_promotion', models.IntegerField(default=1)),
                ('years_with_curr_manager', models.IntegerField(default=3)),
                ('training_times_last_year', models.IntegerField(default=3)),
                ('job_satisfaction', models.IntegerField(default=3)),
                ('environment_satisfaction', models.IntegerField(default=3)),
                ('relationship_satisfaction', models.IntegerField(default=3)),
                ('work_life_balance', models.IntegerField(default=3)),
                ('job_involvement', models.IntegerField(default=3)),
                ('performance_rating', models.IntegerField(default=3)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('type_doc', models.CharField(choices=[('contrat', 'Contrat'), ('cv', 'CV'), ('diplome', 'Diplôme'), ('autre', 'Autre')], default='autre', max_length=20)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='CongeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('En attente', 'En attente'), ('Approuvé', 'Approuvé'), ('Refusé', 'Refusé')], default='En attente', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='BulletinPaie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(max_length=20)),
                ('annee', models.IntegerField()),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_a_payer', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('resultat', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('Satisfaisant', 'Satisfaisant'), ('À surveiller', 'À surveiller'), ('En attente', 'En attente')], default='En attente', max_length=20)),
                ('date_prediction', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
                ('modele', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employees.modeleprediction')),
            ],
        ),
    ]
